export enum IntentType {
  ORDER_STATUS = 'ORDER_STATUS',
  ORDER_CANCEL = 'ORDER_CANCEL',
  RETURN = 'RETURN',
  REFUND = 'REFUND',
  PRODUCT = 'PRODUCT',
  ACCOUNT = 'ACCOUNT',
  PAYMENT = 'PAYMENT',
  GENERAL = 'GENERAL',
}
